### ISSUE TITLE
Support for handheld screens

### ISSUE THREAD

**Issue by Fardinak** [SamsungInternet/web-code#18]
Hey! Great app.
I think it would be great if it played nice on a mobile screen. Right now, the side menu doesn't leave any room for code. Since `web-code` is currently meant for mobile devices, I think that should be something it could handle.

Ever since I found Termux, I was looking for an OTG setup, that lets me take care of small issues with ease and comes in handy when I have an "aha!" moment on the go! Now that may not sound really productive! but I think this could have a larger user base than the owners of a specific device.

**Comment by AdaRoseEdwards** [comment]
Yes this is a good feature, it is definitely not responsively designed right now. 

I will add this in a future release as I work on it but if it is something you want asap I am open to pull requests :)
