### ISSUE TITLE
Cannot install on Node 8.9.4

### ISSUE THREAD

**Issue by lanbau** [SamsungInternet/web-code#22]
Hi i ran  these commands

```
apt update
apt install nodejs
npm i -g web-code
```

attached the error. 
![screenshot_20180206-124459](https://user-images.githubusercontent.com/5410693/35842220-a8a60712-0af8-11e8-824e-02349c3a0e8d.jpg)

**Comment by tanatospl** [comment]
The readme in this repo is not complete. Read this article instead: 

https://medium.com/samsung-internet-dev/writing-software-using-a-phone-e71976f1f18d

You should do something like:
```
termux-fix-shebang `which npm`
```

**Comment by lanbau** [comment]
hi i tried 

```
termux-fix-shebang `which npm`

and 

termux-fix-shebang `which web-code`

```
both gave the same error output (See the above screenshot)

**Comment by tanatospl** [comment]
Try to re-do everything step by step based on the article link which I posted above. It works for me.

**Comment by lanbau** [comment]
hey @tanatospl thanks for the tips. i've uninstalled and cleared the old files/folders, went through all the steps but i'm still getting the same errors. Can i check which node version are you on?

**Comment by tanatospl** [comment]
```
npm -v 
5.5.1
node -v
v8.9.3
```

**Comment by lanbau** [comment]
thanks. i can confirm that this is not working on 9.5.0 too.

**Comment by AdaRoseCannon** [comment]
In your cli it should be 'apt-get' rather than 'apt get'.

I'll test it with recent node versions. Thanks for bringing this to mu attention.

@tanatospl if you want to add anything to the readme please make any changes you like I'll merge the PRs :).

**Comment by lanbau** [comment]
@AdaRoseCannon just curious, have you tested with the latest node versions?

**Comment by AdaRoseCannon** [comment]
I haven't had a chance yet. I have been really busy with other projects.

**Comment by AdaRoseCannon** [comment]
This should now be fixed, let me know if it is still not working and I will re open this ticket. :)
