### ISSUE TITLE
TypeScript support.

### ISSUE THREAD

**Issue by spacemeowx2** [SamsungInternet/web-code#23]
When opening a `.ts` file I will see a play button. 

![19359f0b746f5114e6a7f55969814e38](https://user-images.githubusercontent.com/8019167/38930580-f985b858-4342-11e8-9168-dcd78eac2191.png)

**Comment by pablo-novoa** [comment]
Happen the same to me, please fix this, I need .ts files

**Comment by AdaRoseCannon** [comment]
It thinks their media files. I haven't got time to fix this right now but PRs are welcome.

**Comment by maximmasterr** [comment]
I fixed it

**Comment by AdaRoseCannon** [comment]
Thank you for the PR, merged.
