### ISSUE TITLE
is there a possibility that the project will develop?

### ISSUE THREAD

**Issue by zababurinsv** [SamsungInternet/web-code#35]
i am install on android termux and install vscode and  web-code.

Now i using only web-code.

Why ?

1 - I can work offline.
2 - There is nothing superfluous. (There is not much that is missing)
 
I would very much like this project to continue to develop.
Was it abandoned forever ?

**Comment by AdaRoseCannon** [comment]
It's abandoned sorry. Mostly because I don't need to use it any more, I use a local installation of https://github.com/cdr/code-server instead. It works in the same way but is better almost every way.

**Comment by zababurinsv** [comment]
i use it too.  But I liked this project more.
You have a lot of interesting repositories.
Thank you for what you are))
